### ISSUE TITLE
Deadlock on startup with invalid ENVKEY

### ISSUE THREAD

**Issue by laddhoffman** [envkey/envkey#48]
We're trying to use envkey v2.1.2 in a `node:16.19.0` container.

We are observing the following error:

```
fatal error: all goroutines are asleep - deadlock!	
goroutine 1 [chan send]:	
github.com/envkey/envkey/public/sdks/envkey-source/fetch.httpGetAsync({0xc0000ee0e0, 0xdb}, {0x94e8d0, 0xc0000b4000}, 0xc0000822a0, 0xc000082300, 0x0)	
/Users/daneschneider/projects/envkey/v2/public/sdks/envkey-source/fetch/fetch.go:243 +0x418	
github.com/envkey/envkey/public/sdks/envkey-source/fetch.httpGet({0xc0000ee0e0, 0xdb}, 0x0)	
/Users/daneschneider/projects/envkey/v2/public/sdks/envkey-source/fetch/fetch.go:259 +0x91	
github.com/envkey/envkey/public/sdks/envkey-source/fetch.getJsonBody({0xc0000d6190, 0xc00011b7f0}, {0xc00002a007, 0x43}, {0x0, {0x0, 0x0}, {0x86e203, 0xd}, {0x93d0cc, ...}, ...}, ...)	
/Users/daneschneider/projects/envkey/v2/public/sdks/envkey-source/fetch/fetch.go:552 +0x152	
github.com/envkey/envkey/public/sdks/envkey-source/fetch.getJson({0xc0000d6190, 0x43}, {0xc00002a007, 0x19}, {0x0, {0x0, 0x0}, {0x86e203, 0xd}, {0x93d0cc, ...}, ...}, ...)	
/Users/daneschneider/projects/envkey/v2/public/sdks/envkey-source/fetch/fetch.go:446 +0x13e	
github.com/envkey/envkey/public/sdks/envkey-source/fetch.fetchEnv({0xc00002a007, 0xc314e0}, {0x0, {0x0, 0x0}, {0x86e203, 0xd}, {0x93d0cc, 0x5}, 0x0, ...}, ...)	
/Users/daneschneider/projects/envkey/v2/public/sdks/envkey-source/fetch/fetch.go:356 +0xe5	
github.com/envkey/envkey/public/sdks/envkey-source/fetch.FetchMap({0xc00002a007, 0x62}, {0x0, {0x0, 0x0}, {0x86e203, 0xd}, {0x93d0cc, 0x5}, 0x0, ...})	
/Users/daneschneider/projects/envkey/v2/public/sdks/envkey-source/fetch/fetch.go:82 +0x312	
github.com/envkey/envkey/public/sdks/envkey-source/cmd.run(0x7a5820, {0xc0000ae660, 0xc00011bd60, 0x6}, 0x1)	
/Users/daneschneider/projects/envkey/v2/public/sdks/envkey-source/cmd/run.go:119 +0x4a5	
/opt/node_modules/envkey/loader.js:170
```

**Comment by laddhoffman** [comment]
So it turns out I had an incorrect value in the `ENVKEY` environment variable. After correcting that, I'm no longer seeing this error. Still, this is not the error one would expect for an incorrect value.

Regards!

**Comment by danenania** [comment]
Thanks for reporting the issue and the update @laddhoffman--we'll investigate.

**Comment by antoinedelplace** [comment]
I have the same issue
