### ISSUE TITLE
UI client upgrade error

### ISSUE THREAD

**Issue by tdutreui-solocal** [envkey/envkey#59]
After migrating to a V2 organization :
- Upgrade your desktop UI client to V2 (here v2.4.4)
- When you launch it after, the following appears :
![image](https://user-images.githubusercontent.com/102948575/230046811-3a35b21c-f8ff-446f-9359-f7fb9a558466.png)
- click "Upgrade all", the following popup shows up :
![image](https://user-images.githubusercontent.com/102948575/230046968-a4d44955-7828-4f00-873e-8faab2072498.png)

Logs (I censored some ids as I did not know if it were sensitive):
```
will write to log file at  /home/thomas/.envkey/logs/desktop-2023-04-05.log
{"ts":"2023-04-05T09:53:24.171Z","proc":"main","msg":"logger initialized with name desktop"}
{"ts":"2023-04-05T09:53:24.422Z","proc":"main","msg":"on:ready","version":"2.4.4"}
{"ts":"2023-04-05T09:53:24.750Z","proc":"main","msg":"startCore"}
{"ts":"2023-04-05T09:53:25.075Z","proc":"main","msg":"Core process status","alive":"2.4.2"}
{"ts":"2023-04-05T09:53:25.075Z","proc":"main","msg":"Core process is already running"}
{"ts":"2023-04-05T09:53:25.076Z","proc":"main","msg":"Starting core process alive check loop..."}
{"ts":"2023-04-05T09:53:25.076Z","proc":"main","msg":"core is running","currentAppVersion":"2.4.4"}
{"ts":"2023-04-05T09:53:25.077Z","proc":"main","msg":"Fetching root-device-key from file store..."}
{"ts":"2023-04-05T09:53:25.101Z","proc":"main","msg":"Fallback store initialized.","path":"/home/thomas/.config/envkey/envkey-keystore-fallback.json"}
{"ts":"2023-04-05T09:53:25.119Z","proc":"main","msg":"Fetched root-device-key."}
{"ts":"2023-04-05T09:53:25.131Z","proc":"main","msg":"Setting User-Agent with OS keyring auth token"}
{"ts":"2023-04-05T09:53:25.139Z","proc":"main","msg":"init updates loop"}
{"ts":"2023-04-05T09:53:25.144Z","proc":"main","msg":"app update loop initialized"}
{"ts":"2023-04-05T09:53:25.146Z","proc":"main","msg":"autoUpdater:info","data":["Checking for update"]}
{"ts":"2023-04-05T09:53:25.710Z","proc":"main","msg":"","currentVersion":"2.4.2","nextVersion":"2.4.3"}
{"ts":"2023-04-05T09:53:25.716Z","proc":"main","msg":"installMissingOrOutdatedCliTools","bundledCliInstalled":true,"cliLatestInstalledRes":{"nextVersion":"2.4.3","currentVersion":"2.4.2"},"cliVersion":"2.4.2","isUpgradingCli":false,"shouldInstallCli":false,"envkeySourceLatestInstalledRes":{"nextVersion":"2.3.0","currentVersion":"2.1.1"},"shouldInstallEnvkeysource":false}
{"ts":"2023-04-05T09:53:25.716Z","proc":"main","msg":"CLI tools already installed"}
{"ts":"2023-04-05T09:53:25.728Z","proc":"main","msg":"autoUpdater:info","data":["Update for version 2.4.4 is not available (latest version: 2.4.4, downgrade is disallowed)."]}
{"ts":"2023-04-05T09:53:25.756Z","proc":"main","msg":"","currentVersion":"2.4.2","nextVersion":"2.4.3"}
{"ts":"2023-04-05T09:53:25.757Z","proc":"main","msg":"finished checking updates","hasDesktopUpgrade":false,"hasCliUpgrade":true,"hasEnvkeysourceUpgrade":true}
{"ts":"2023-04-05T09:53:27.342Z","proc":"main","msg":"[ui-console] RWS>","data":["connect",0]}
{"ts":"2023-04-05T09:53:27.342Z","proc":"main","msg":"[ui-console] RWS>","data":["next delay",0]}
{"ts":"2023-04-05T09:53:27.342Z","proc":"main","msg":"[ui-console] fetching core state","data":{"accountId":"[CENSORED]"},"ui-ts":"2023-04-05T09:53:26.303Z"}
{"ts":"2023-04-05T09:53:27.342Z","proc":"main","msg":"[ui-console] RWS>","data":["connect",{"url":"ws://localhost:19048"}]}
{"ts":"2023-04-05T09:53:27.342Z","proc":"main","msg":"[ui-console] RWS>","data":"addListeners"}
{"ts":"2023-04-05T09:53:27.342Z","proc":"main","msg":"[ui-console] RWS>","data":"open event"}
{"ts":"2023-04-05T09:53:27.342Z","proc":"main","msg":"[ui-console] fetching core state","data":{"accountId":"[CENSORED]"},"ui-ts":"2023-04-05T09:53:26.340Z"}
{"ts":"2023-04-05T09:53:27.343Z","proc":"main","msg":"[ui-console] fetched core state, applying update","data":{"accountId":"[CENSORED]"},"ui-ts":"2023-04-05T09:53:26.374Z"}
{"ts":"2023-04-05T09:53:27.343Z","proc":"main","msg":"[ui-console] updating core state","data":{"bytes":348748},"ui-ts":"2023-04-05T09:53:26.374Z"}
{"ts":"2023-04-05T09:53:27.343Z","proc":"main","msg":"[ui-console] redirecting to org:","data":"/org/[CENSORED]","ui-ts":"2023-04-05T09:53:26.413Z"}
{"ts":"2023-04-05T09:53:27.343Z","proc":"main","msg":"[ui-console] got pending update and conflicts info","data":[],"ui-ts":"2023-04-05T09:53:26.438Z"}
{"ts":"2023-04-05T09:53:27.343Z","proc":"main","msg":"[ui-console] signed_in_account_container: won't render yet","auth":true,"auth.token":true,"shouldFetchSession":false,"currentUser":{"type":"orgUser","id":"[CENSORED]","createdAt":1680679437368,"updatedAt":1680680891531,"deletedAt":0,"email":"[CENSORED]","uid":"[CENSORED]","provider":"email","firstName":"Thomas","lastName":"Dutreuilh","invitedById":"[CENSORED]","isCreator":false,"inviteAcceptedAt":1680680891531,"orgRoleId":"[CENSORED]","orgRoleUpdatedAt":1680679437368,"importId":"[CENSORED]"},"auth.orgId":"[CENSORED]","orgId":"[CENSORED]","shouldRedirectPath":false,"uiTree":false}
{"ts":"2023-04-05T09:53:27.343Z","proc":"main","msg":"[ui-console] dispatch:","data":"envkey/client/SET_UI_LAST_SELECTED_URL","ui-ts":"2023-04-05T09:53:26.440Z"}
{"ts":"2023-04-05T09:53:27.343Z","proc":"main","msg":"[ui-console] applied core state update","data":{"accountId":"[CENSORED]"},"ui-ts":"2023-04-05T09:53:26.805Z"}
{"ts":"2023-04-05T09:53:27.343Z","proc":"main","msg":"[ui-console] fetched core state, applying update","data":{"accountId":"[CENSORED]"},"ui-ts":"2023-04-05T09:53:26.961Z"}
{"ts":"2023-04-05T09:53:27.343Z","proc":"main","msg":"[ui-console] updating core state","data":{"bytes":348748},"ui-ts":"2023-04-05T09:53:26.961Z"}
{"ts":"2023-04-05T09:53:27.343Z","proc":"main","msg":"[ui-console] applied core state update","data":{"accountId":"[CENSORED]"},"ui-ts":"2023-04-05T09:53:27.027Z"}
{"ts":"2023-04-05T09:53:27.343Z","proc":"main","msg":"[ui-console] core result:","data":"envkey/client/SET_UI_LAST_SELECTED_URL","ui-ts":"2023-04-05T09:53:27.027Z"}
{"ts":"2023-04-05T09:53:27.515Z","proc":"main","msg":"client upgrade available","cli":{"nextVersion":"2.4.3","currentVersion":"2.4.2","notes":{"2.4.3":"- Fixes for v1 > v2 upgrade error handling\n- Logging improvements\n- Fix for rare crash when the OS wakes from sleep"}},"envkeysource":{"nextVersion":"2.3.0","currentVersion":"2.1.1","notes":{"2.3.0":"Automatic upgrades from EnvKey v1","2.1.3":"Fix for --force / -f flag applying overrides when it shouldn't","2.1.2":"Fix for overrides from .env file not being correctly applied"}}}
{"ts":"2023-04-05T09:53:28.523Z","proc":"main","msg":"[ui-console] Root - upgrade available","data":{"cli":{"nextVersion":"2.4.3","currentVersion":"2.4.2","notes":{"2.4.3":"- Fixes for v1 > v2 upgrade error handling\n- Logging improvements\n- Fix for rare crash when the OS wakes from sleep"}},"envkeysource":{"nextVersion":"2.3.0","currentVersion":"2.1.1","notes":{"2.3.0":"Automatic upgrades from EnvKey v1","2.1.3":"Fix for --force / -f flag applying overrides when it shouldn't","2.1.2":"Fix for overrides from .env file not being correctly applied"}}},"ui-ts":"2023-04-05T09:53:27.517Z"}
{"ts":"2023-04-05T09:53:32.430Z","proc":"main","msg":"[ui-console] RWS>","data":"accept open"}
{"ts":"2023-04-05T09:53:54.804Z","proc":"main","msg":"autoUpdater:error  ","data":["Error: Error: Please check update first\n    at l.downloadUpdate (/tmp/.mount_EnvKeyZeH9Fg/resources/app/bundle.js:3:247948)\n    at /tmp/.mount_EnvKeyZeH9Fg/resources/app/bundle.js:275:71981\n    at Generator.next (<anonymous>)\n    at /tmp/.mount_EnvKeyZeH9Fg/resources/app/bundle.js:275:68803\n    at new Promise (<anonymous>)\n    at o (/tmp/.mount_EnvKeyZeH9Fg/resources/app/bundle.js:275:68548)\n    at Object.t.downloadAndInstallUpgrade (/tmp/.mount_EnvKeyZeH9Fg/resources/app/bundle.js:275:71739)\n    at IpcMainImpl.<anonymous> (/tmp/.mount_EnvKeyZeH9Fg/resources/app/bundle.js:3:156660)\n    at IpcMainImpl.emit (events.js:315:20)\n    at IpcMainImpl.EventEmitter.emit (domain.js:467:12)"]}
{"ts":"2023-04-05T09:53:54.806Z","proc":"main","msg":"autoUpdater download failed","err":{"name":"Error","message":"Please check update first","stack":"Error: Please check update first\n    at l.downloadUpdate (/tmp/.mount_EnvKeyZeH9Fg/resources/app/bundle.js:3:247948)\n    at /tmp/.mount_EnvKeyZeH9Fg/resources/app/bundle.js:275:71981\n    at Generator.next (<anonymous>)\n    at /tmp/.mount_EnvKeyZeH9Fg/resources/app/bundle.js:275:68803\n    at new Promise (<anonymous>)\n    at o (/tmp/.mount_EnvKeyZeH9Fg/resources/app/bundle.js:275:68548)\n    at Object.t.downloadAndInstallUpgrade (/tmp/.mount_EnvKeyZeH9Fg/resources/app/bundle.js:275:71739)\n    at IpcMainImpl.<anonymous> (/tmp/.mount_EnvKeyZeH9Fg/resources/app/bundle.js:3:156660)\n    at IpcMainImpl.emit (events.js:315:20)\n    at IpcMainImpl.EventEmitter.emit (domain.js:467:12)"}}
{"ts":"2023-04-05T09:53:54.807Z","proc":"main","msg":"autoUpdater download","error":true}
{"ts":"2023-04-05T09:53:54.807Z","proc":"main","msg":"Sending upgrade-error to webContents","win":true}
{"ts":"2023-04-05T09:53:54.832Z","proc":"main","msg":"autoUpdater:info","data":["Checking for update"]}
{"ts":"2023-04-05T09:53:55.558Z","proc":"main","msg":"autoUpdater:info","data":["Update for version 2.4.4 is not available (latest version: 2.4.4, downgrade is disallowed)."]}
{"ts":"2023-04-05T09:53:55.695Z","proc":"main","msg":"","currentVersion":"2.4.2","nextVersion":"2.4.3"}
{"ts":"2023-04-05T09:53:55.695Z","proc":"main","msg":"finished checking updates","hasDesktopUpgrade":false,"hasCliUpgrade":true,"hasEnvkeysourceUpgrade":true}
{"ts":"2023-04-05T09:53:56.997Z","proc":"main","msg":"client upgrade available","cli":{"nextVersion":"2.4.3","currentVersion":"2.4.2","notes":{"2.4.3":"- Fixes for v1 > v2 upgrade error handling\n- Logging improvements\n- Fix for rare crash when the OS wakes from sleep"}},"envkeysource":{"nextVersion":"2.3.0","currentVersion":"2.1.1","notes":{"2.3.0":"Automatic upgrades from EnvKey v1","2.1.3":"Fix for --force / -f flag applying overrides when it shouldn't","2.1.2":"Fix for overrides from .env file not being correctly applied"}}}
```

**Comment by tdutreui-solocal** [comment]
Never mind, it was due to my previous tests by installing envkey-source manually on my local computer.
I solved it by removing it :
```
~$ which envkey-source 
/usr/local/bin/envkey-source
~$ rm /usr/local/bin/envkey-source
```
