### ISSUE TITLE
Security leak: ENVKEY value is logged when envkey-fetch binary fails

### ISSUE THREAD

**Issue by nahuel** [envkey/envkey#65]
In this block of code:

https://github.com/envkey/envkey/blob/599e585feafa0eb3f3f4b6ca73c49f97d1d54505/public/sdks/languages-and-frameworks/python/pkg/envkey/fetch.py#L68-L72

when `envkey-fetch` returns a non-zero status, a `ValueError` exception is raised inside the `except` block, but that `ValueError` exception instance is chained automatically to the original `subprocess.CalledProcessError`, so both exceptions will be logged if the `ValueError` exception kills the process (or is printed somewhere). In that case something like this will be printed out:

```
 Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/envkey/fetch.py", line 55, in fetch_env
    res = subprocess.check_output(args).decode(encoding="utf-8").rstrip()
  File "/opt/python3.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/opt/python3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/env/lib/python3.7/site-packages/envkey/ext/envkey-fetch_1.2.9_linux_amd64/envkey-fetch', 'XXXXXXXXXXXXXXXXXXXX-YYYYYYYYYYYYYYYY', '--client-name', 'envkey-python', '--client-version', '1.3.2', '--cache']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

(...)
  File "/usr/local/lib/python3.9/site-packages/envkey/__init__.py", line 7, in <module>
    load(is_init=True)
  File "/usr/local/lib/python3.9/site-packages/envkey/loader.py", line 26, in load
    fetch_res = fetch_env(key, cache_enabled=cache_enabled)
  File "/usr/local/lib/python3.9/site-packages/envkey/fetch.py", line 58, in fetch_env
    raise ValueError("ENVKEY invalid. Couldn't load vars.")
ValueError: ENVKEY invalid. Couldn't load vars. 
```

As you can see, printing the first exception leaks the ENVKEY value (`'XXXXXXXXXXXXXXXXXXXX-YYYYYYYYYYYYYYYY'`) to the log

**Comment by nahuel** [comment]
added small PR to fix this: https://github.com/envkey/envkey/pull/66

**Comment by danenania** [comment]
Thanks @nahuel! This is only affecting v1 of the envkey-python, since in v2 of the library the `ENVKEY` is passed to the subprocess via the environment rather than a command argument:

```
def fetch_env(envkey_arg=None, cache_enabled=False, dot_env_path=None):
  try: 
    env = {"ENVKEY": envkey_arg if envkey_arg else os.environ["ENVKEY"]}
  except KeyError:
    env = {}

  for key in os.environ.keys():
    if key != "ENVKEY":
      env[key] = os.environ[key]

  path = __lib_path()
  args = [path, "--json", "--client-name", "envkey-python", "--client-version", pkg_resources.get_distribution("envkey").version]
  if cache_enabled:
    args.append("--cache")

  if dot_env_path:
    args.append("--env-file")
    args.append(dot_env_path)

  try:
    res = subprocess.check_output(args, env=env).decode(encoding="utf-8").rstrip()
  except subprocess.CalledProcessError as err:
    print("envkey-source " + err.output.decode(encoding="utf-8"), file=sys.stderr)
    raise ValueError("ENVKEY invalid. Couldn't load vars.") from None

  if res.startswith("error: "):
    raise ValueError("ENVKEY invalid. Couldn't load vars.")

  return json.loads(res)
 ```
 
That said, your PR is still an improvement in terms of error handling, so we've merged this and will incorporate it into the next envkey-python release. Thanks again!

**Comment by nahuel** [comment]
Thanks, you are right, I found/tested the error only on the v1 version.
