### ISSUE TITLE
Basic User cannot create local override

### ISSUE THREAD

**Issue by matzeeable** [envkey/envkey#67]
Reproduce:

1. Install Envkey UI and connect to self-hosted Envkey as a **Basic User**
1. Navigate to a **block** (not tested with an app)
1. Create a [Local override](https://docs-v2.envkey.com/docs/branches-and-local-overrides#local-overrides) variable
1. After clicking on "Commit", we run into an error dialog

See log:

```
{"ts":"2023-05-22T08:17:45.376Z","proc":"main","msg":"Comitting local-state to file store..."}
{"ts":"2023-05-22T08:17:45.381Z","proc":"main","msg":"local-state encrypted and committed."}
{"ts":"2023-05-22T08:18:24.797Z","proc":"main","msg":"POST /action"}
{"ts":"2023-05-22T08:18:24.798Z","proc":"main","msg":"Received","action":"envkey/client/COMMIT_ENVS"}
{"ts":"2023-05-22T08:18:24.819Z","proc":"main","msg":"Missing changesets symmetric key for pending changes","environmentId":"xxxxxxxxxxxx","pending":true,"stack":"Error: Missing changesets symmetric key for pending changes\n    at C:\\snapshot\\v2\\private\\ci_cd\\cli-builder\\build\\workspace\\webpack:\\core_process\\src\\lib\\envs\\encrypted_keys.ts:200:21\n    at Generator.next (<anonymous>)\n    at C:\\snapshot\\v2\\private\\ci_cd\\cli-builder\\build\\workspace\\envkey-core.js:185863:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\snapshot\\v2\\private\\ci_cd\\cli-builder\\build\\workspace\\envkey-core.js:185859:12)\n    at Object.encryptedKeyParamsForEnvironments (C:\\snapshot\\v2\\private\\ci_cd\\cli-builder\\build\\workspace\\webpack:\\core_process\\src\\lib\\envs\\encrypted_keys.ts:64:6)\n    at C:\\snapshot\\v2\\private\\ci_cd\\cli-builder\\build\\workspace\\webpack:\\core_process\\src\\lib\\envs\\params.ts:98:13\n    at Generator.next (<anonymous>)\n    at C:\\snapshot\\v2\\private\\ci_cd\\cli-builder\\build\\workspace\\envkey-core.js:187614:71\n    at new Promise (<anonymous>)"}
{"ts":"2023-05-22T08:18:24.820Z","proc":"main","msg":"Core Process Unhandled Error","alert":true,"err":{"name":"Error","message":"Missing changesets symmetric key for pending changes","stack":"Error: Missing changesets symmetric key for pending changes\n    at C:\\snapshot\\v2\\private\\ci_cd\\cli-builder\\build\\workspace\\webpack:\\core_process\\src\\lib\\envs\\encrypted_keys.ts:200:21\n    at Generator.next (<anonymous>)\n    at C:\\snapshot\\v2\\private\\ci_cd\\cli-builder\\build\\workspace\\envkey-core.js:185863:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\snapshot\\v2\\private\\ci_cd\\cli-builder\\build\\workspace\\envkey-core.js:185859:12)\n    at Object.encryptedKeyParamsForEnvironments (C:\\snapshot\\v2\\private\\ci_cd\\cli-builder\\build\\workspace\\webpack:\\core_process\\src\\lib\\envs\\encrypted_keys.ts:64:6)\n    at C:\\snapshot\\v2\\private\\ci_cd\\cli-builder\\build\\workspace\\webpack:\\core_process\\src\\lib\\envs\\params.ts:98:13\n    at Generator.next (<anonymous>)\n    at C:\\snapshot\\v2\\private\\ci_cd\\cli-builder\\build\\workspace\\envkey-core.js:187614:71\n    at new Promise (<anonymous>)"}}
{"ts":"2023-05-22T08:18:24.820Z","proc":"main","msg":"Shutting down gracefully..."}
{"ts":"2023-05-22T08:18:24.821Z","proc":"main","msg":"Persisting final state before shutdown..."}
{"ts":"2023-05-22T08:18:24.822Z","proc":"main","msg":"Comitting local-state to file store..."}
```

```
{"ts":"2023-05-22T08:17:46.350Z","proc":"main","msg":"[ui-console] core result:","data":"envkey/client/CREATE_ENTRY_ROW","ui-ts":"2023-05-22T08:17:45.377Z"}
{"ts":"2023-05-22T08:17:46.350Z","proc":"main","msg":"[ui-console] envkey/client/CREATE_ENTRY_ROW","data":"4 diffs to apply","ui-ts":"2023-05-22T08:17:45.377Z"}
{"ts":"2023-05-22T08:17:46.350Z","proc":"main","msg":"[ui-console] applied patch","data":[],"ui-ts":"2023-05-22T08:17:45.390Z"}
{"ts":"2023-05-22T08:17:46.350Z","proc":"main","msg":"[ui-console] updating core state","data":{"bytes":229469},"ui-ts":"2023-05-22T08:17:45.390Z"}
{"ts":"2023-05-22T08:17:46.350Z","proc":"main","msg":"[ui-console] got pending update and conflicts info","data":[],"ui-ts":"2023-05-22T08:17:45.399Z"}
{"ts":"2023-05-22T08:17:46.350Z","proc":"main","msg":"[ui-console] set new state","data":[],"ui-ts":"2023-05-22T08:17:45.406Z"}
{"ts":"2023-05-22T08:19:04.699Z","proc":"main","msg":"[ui-console] dispatch:","data":"envkey/client/COMMIT_ENVS","ui-ts":"2023-05-22T08:18:24.796Z"}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] RWS>","data":"message event"}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] received 4 socket message diffs","data":[],"ui-ts":"2023-05-22T08:18:24.827Z"}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] applied socket message diffs","data":[],"ui-ts":"2023-05-22T08:18:24.827Z"}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] updating core state","data":{"bytes":229582},"ui-ts":"2023-05-22T08:18:24.827Z"}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] set new state","data":[],"ui-ts":"2023-05-22T08:18:24.839Z"}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] RWS>","data":"message event"}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] received 4 socket message diffs","data":[],"ui-ts":"2023-05-22T08:18:24.849Z"}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] applied socket message diffs","data":[],"ui-ts":"2023-05-22T08:18:24.849Z"}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] set new state","data":[],"ui-ts":"2023-05-22T08:18:24.849Z"}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] RWS>","data":"message event"}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] Received unknown socket message for core proc: ","data":"{\"type\":\"closing\"}","ui-ts":"2023-05-22T08:18:24.852Z"}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] RWS>","data":"close event"}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] RWS>","data":["connect",1]}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] RWS>","data":"removeListeners"}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] RWS>","data":["next delay",2533.139208349924]}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] RWS>","data":"message event"}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] Received unknown socket message for core proc: ","data":"{\"type\":\"closing\"}","ui-ts":"2023-05-22T08:18:24.852Z"}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] RWS>","data":"close event"}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] RWS>","data":["connect",1]}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] RWS>","data":"removeListeners"}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] RWS>","data":["next delay",2533.139208349924]}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] core result:","data":"envkey/client/COMMIT_ENVS","ui-ts":"2023-05-22T08:18:24.854Z"}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] reporting error to electron","data":[]}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] RWS>","data":["connect",{"url":"ws://localhost:19048"}]}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] RWS>","data":"addListeners"}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] RWS>","data":["connect",{"url":"ws://localhost:19048"}]}
{"ts":"2023-05-22T08:19:04.700Z","proc":"main","msg":"[ui-console] RWS>","data":"addListeners"}
```

Then, we added the Local override variable for the basic user with an admin user. When running `envkey-source` the variable is not loaded. But, when updating the basic user to an admin user **and** regenerating the app `ENVKEY` the Local override variable is readed.

**Comment by danenania** [comment]
Thank you @matzeeable for the info and repro steps--we're investigating.

**Comment by danenania** [comment]
Hey @matzeeable, we've been looking into this but so far haven't been able to reproduce it. If you could look at the logs and let me know the order that the following actions occurred, and the role of the user that executed them, that might be helpful to pinning it down:

- Block connected to app
- Basic user invited
- Basic user accepted invite
- Basic user given access to app (unless it was granted during invite)
- Updates to user's block locals prior to the error (if any)

Also, if there were any access changes, like the user's app access was removed then re-added, or app was disconnected from the block then re-connected, org role changed, etc. that would also be good to know.

Thanks!
