### ISSUE TITLE
Not able to setup EnvKey in Remix application

### ISSUE THREAD

**Issue by mzvdev** [envkey/envkey#80]
Hi,

I tried to to use EnvKey with the [Remix Blues Stack](https://github.com/remix-run/blues-stack).

When I add _**import "envkey";**_ in server.ts I get this error when I run _**$ npm run dev.**_
(I have added in .env file the ENVKEY=*******************)

```
Error: spawnSync /Users/Gitlab/app/build/ext/envkey-source_2.4.1_darwin_arm64/envkey-source ENOENT
    at Object.spawnSync (node:internal/child_process:1110:20)
    at spawnSync (node:child_process:871:24)
    at execFileSync (node:child_process:914:15)
    at fetch2 (/Users/Gitlab/app/build/server.js:45202:21)
    at Object.load (/Users/Gitlab/app/build/server.js:45066:31)
    at node_modules/envkey/index.js (/Users/Gitlab/app/build/server.js:45232:40)
    at __require (/Users/Gitlab/app/build/server.js:9:50)
    at Object.<anonymous> (/Users/Gitlab/app/build/server.js:45243:29)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
Error: spawnSync /Users/Gitlab/app/build/ext/envkey-source_2.4.1_darwin_arm64/envkey-source ENOENT
    at Object.spawnSync (node:internal/child_process:1110:20)
    at spawnSync (node:child_process:871:24)
    at execFileSync (node:child_process:914:15)
    at fetch2 (/Users/Gitlab/app/build/server.js:45202:21)
    at Object.load (/Users/Gitlab/app/build/server.js:45066:31)
    at node_modules/envkey/index.js (/Users/Gitlab/app/build/server.js:45232:40)
    at __require (/Users/Gitlab/app/build/server.js:9:50)
    at Object.<anonymous> (/Users/Gitlab/app/build/server.js:45243:29)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
ERROR: "dev:server" exited with 1.
```

Maybe the issue is because Remix use in the package.json file dotenv and cross-env
```
    "scripts": {
    "build": "run-s build:*",
    "build:remix": "remix build",
    "build:server": "esbuild --platform=node --format=cjs ./server.ts --outdir=build --bundle",
    "dev": "run-p dev:*",
    "dev:build": "cross-env NODE_ENV=development npm run build:server -- --watch",
    "dev:remix": "cross-env NODE_ENV=development remix watch",
    "dev:server": "cross-env NODE_ENV=development node --inspect --require ./node_modules/dotenv/config --require ./mocks ./build/server.js",
    "docker": "docker-compose up -d",
    "format": "prettier --write .",
    "lint": "eslint --cache --cache-location ./node_modules/.cache/eslint .",
    "setup": "prisma generate && prisma migrate deploy && prisma db seed",
    "start": "cross-env NODE_ENV=production node ./build/server.js",
    "start:mocks": "cross-env NODE_ENV=production node --require ./mocks --require dotenv/config ./build/server.js",
    "test": "vitest",
    "test:e2e:dev": "start-server-and-test dev http://localhost:3000 \"npx cypress open\"",
    "pretest:e2e:run": "npm run build",
    "test:e2e:run": "cross-env PORT=8811 start-server-and-test start:mocks http://localhost:8811 \"npx cypress run\"",
    "typecheck": "tsc && tsc -p cypress",
    "validate": "run-p \"test -- --run\" lint typecheck test:e2e:run"
  },
```

**Comment by danenania** [comment]
Hi @mzvdev, it looks like the `envkey-source` binary that the envkey-node library wraps is not being included when remix bundles your server-side app with esbuild. These binaries are in the `ext` directory of the `envkey` node module. You'll need to copy the required binaries for dev/production into the build dir as part of your build. You could add something like:

```
"scripts": {
...

"build:server": "esbuild --platform=node --format=cjs ./server.ts --outdir=build --bundle && cp -R ./node_modules/envkey/ext ./build/",

}
```

**Comment by danenania** [comment]
You could also do this through an esbuild plugin like this one: https://github.com/LinbuduLab/esbuild-plugins/tree/main/packages/esbuild-plugin-copy

But I'm not sure if Remix allows customizing the esbuild config.
